
alias = "gfunction"

[name]
first = "ryan"
last = "taylor"

[accounts]
github = ["rtaylor034", "sixslime"]
discord = "gfunction"
minecraft = "SixSlime"
tryhackme = "ryan.mm.taylor"
riot_id = "Command Block#137"