
alias = "gfunction"
[name]
first = "ryan"
last = "taylor"

[accounts]
github = ["rtaylor034", "sixslime"]
linkedin = "rtaylor034"
discord = "gfunction"
minecraft = "SixSlime"
riot_id = "Command Block#137"